// examples/nextjs-app/app/page.tsx
'use client'

import { useSession, signOut, signIn } from 'next-auth/react'
import { Button } from '@/components/ui/button'

export default function Home() {
  const session = useSession()
  const user = session.data?.user
  const isAuthenticated = !!user

  return (
    <div className="bg-slate-100 min-h-screen">
      <main role="main" className="flex flex-col items-center justify-center h-5/6 space-y-8 text-center px-4 py-16 lg:pt-32 md:pt-16 sm:pt-8">
        <h1 className="mt-4 text-2xl font-extrabold tracking-tight text-slate-900 sm:text-5xl xl:max-w-[43.5rem]">
          Next.js Application Example using OpenID Connect
        </h1>
        <p className="mt-4 max-w-lg text-lg text-slate-700">
          This example demonstrates how to authenticate users in a Next.js Application using OpenID Connect Protocol.
        </p>
        {isAuthenticated ? (
          <Button data-testid="logout-button" onClick={() => signOut()}>
            Logout
          </Button>
        ) : (
          <Button data-testid="login-button" onClick={() => signIn('testid')}>
            Login with TestID
          </Button>
        )}
        <p className="mt-4 max-w-lg text-slate-700">
          If you want to checkout out how to implement OpenID Connect in your Next.js app, take a look at the <a className="text-indigo-600" href="https://github.com/cerberauth/openid-connect-examples/tree/main/examples/nextjs-app">source code</a>.
        </p>
      </main>

      <footer className="text-center py-4">
        <p className="text-sm text-gray-500">
          Proudly part of <a className="text-indigo-600" href="https://www.cerberauth.com">CerberAuth</a> community.
        </p>
      </footer>
    </div>
  )
}

// examples/angular-spa/src/app/app.component.ts
import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { OAuthService } from 'angular-oauth2-oidc';
import { filter } from 'rxjs';

import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, NgIf],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'Angular SPA with OAuth2 / OpenID Connect';

  constructor(private oauthService: OAuthService) {
    this.oauthService.configure(environment.auth);
    this.oauthService.setupAutomaticSilentRefresh();
    this.oauthService.loadDiscoveryDocumentAndTryLogin({ customHashFragment: window.location.search });

    this.oauthService.events
      .pipe(filter((e) => e.type === 'token_received'))
      .subscribe((_) => this.oauthService.loadUserProfile());
  }

  login() {
    this.oauthService.initLoginFlow();
  }

  logout() {
    this.oauthService.logOut();
  }

  get user() {
    return this.oauthService.getIdentityClaims();
  }
}

<style></style>

<main class="main">
  <div class="bg-slate-100 min-h-screen">
    <main role="main"
      class="flex flex-col items-center justify-center h-5/6 space-y-8 text-center px-4 py-16 lg:pt-32 md:pt-16 sm:pt-8">
      <h1 class="mt-4 text-2xl font-extrabold tracking-tight text-slate-900 sm:text-5xl xl:max-w-[43.5rem]">
        Angular SPA Example using OpenID Connect
      </h1>
      <p class="mt-4 max-w-lg text-lg text-slate-700">
        This example demonstrates how to authenticate users in a Angular Single Page Application (SPA) using OpenID
        Connect Protocol.
      </p>

      <button *ngIf="user; else loginButton" (click)="logout()"
        class="inline-flex justify-center rounded-lg text-sm font-semibold py-3 px-4 bg-slate-900 text-white hover:bg-slate-700">
        Logout
      </button>
      <ng-template #loginButton>
        <button (click)="login()"
          class="inline-flex justify-center rounded-lg text-sm font-semibold py-3 px-4 bg-slate-900 text-white hover:bg-slate-700">
          Login with TestID
        </button>
      </ng-template>

      <p class="mt-4 max-w-lg text-slate-700">
        If you want to checkout out how to implement OpenID Connect in your Angular SPA, take a look at the <a
          class="text-indigo-600"
          href="https://github.com/cerberauth/openid-connect-examples/tree/main/examples/angular-spa">source code</a>.
      </p>
    </main>

    <footer class="text-center py-4">
      <p class="text-sm text-gray-500">
        Proudly part of <a class="text-indigo-600" href="https://www.cerberauth.com">CerberAuth</a> community.
      </p>
    </footer>
  </div>
</main>

<router-outlet />
